### ISSUE TITLE
Failed Installation 

### ISSUE THREAD

**Issue by JamesBedont** [kmorey/secure-copy#2]
I couldn't install this plugin I got the following output:

> git-utils@2.1.4 install C:\Users\James\AppData\Local\Temp\apm-install-dir-115415-2860-186pane\node_modules\secure-copy\node_modules\git-utils
> node-gyp rebuild

C:\Users\James\AppData\Local\Temp\apm-install-dir-115415-2860-186pane\node_modules\secure-copy\node_modules\git-utils>node "C:\Users\James\AppData\Local\atom\app-0.199.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm WARN deprecated byline@4.1.1: critical bug fixed in v4.2.0
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\James\\AppData\\Local\\atom\\app-0.199.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\James\\AppData\\Local\\atom\\app-0.199.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\James\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\James\\.atom\\.apmrc" "install" "C:\\Users\\James\\AppData\\Local\\Temp\\d-115415-2860-tbz4m6\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! git-utils@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-utils@2.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

**Comment by kmorey** [comment]
Looks like I had to update an internal dependency. Give it a shot now.
